const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.Text,
		C3.Behaviors.Pin,
		C3.Behaviors.Platform,
		C3.Behaviors.Bullet,
		C3.Behaviors.Timer,
		C3.Plugins.NinePatch,
		C3.Plugins.TiledBg,
		C3.Plugins.Touch,
		C3.Plugins.Button,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Browser,
		C3.Behaviors.solid,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Browser.Acts.ExecJs,
		C3.Plugins.System.Cnds.PickAll,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.Pin.Acts.SetDestroy,
		C3.Behaviors.Pin.Acts.PinByDistance,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.Sprite.Exps.ObjectTypeName,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Arr.Cnds.IsEmpty,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Exps.CurY,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar
	];
};
self.C3_JsPropNameTable = [
	{part: 0},
	{row: 0},
	{template: 0},
	{index: 0},
	{platform_regular: 0},
	{platformIndustrial_: 0},
	{platformIndustrial_10: 0},
	{platformIndustrial_11: 0},
	{platformIndustrial_12: 0},
	{platformIndustrial_13: 0},
	{platformIndustrial_14: 0},
	{spike_up: 0},
	{platformIndustrial_16: 0},
	{platformIndustrial_17: 0},
	{platformIndustrial_18: 0},
	{platformIndustrial_19: 0},
	{platformIndustrial_2: 0},
	{platformIndustrial_20: 0},
	{platformIndustrial_21: 0},
	{platformIndustrial_22: 0},
	{platformIndustrial_23: 0},
	{platformIndustrial_24: 0},
	{platformIndustrial_25: 0},
	{spike_right: 0},
	{spike_down: 0},
	{spike_left: 0},
	{platformIndustrial_3: 0},
	{platformIndustrial_4: 0},
	{platformIndustrial_5: 0},
	{platformIndustrial_6: 0},
	{platformIndustrial_7: 0},
	{platformIndustrial_8: 0},
	{platformIndustrial_9: 0},
	{Mouse: 0},
	{AJAX: 0},
	{PartQueue: 0},
	{Sequences: 0},
	{jewelOrange: 0},
	{jewelPink: 0},
	{jewelYellow: 0},
	{debug_label: 0},
	{destroyer: 0},
	{Generator: 0},
	{generic_text: 0},
	{handled: 0},
	{Pin: 0},
	{placeholder: 0},
	{Platform: 0},
	{player: 0},
	{Bullet: 0},
	{puller: 0},
	{score_text: 0},
	{spawner: 0},
	{PlayerKiller: 0},
	{springBoard: 0},
	{Timer: 0},
	{timerObject: 0},
	{button_restart: 0},
	{dialog_background: 0},
	{help_text: 0},
	{TiledBackground: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Touch: 0},
	{Button: 0},
	{PauseText: 0},
	{PauseButton: 0},
	{Jump: 0},
	{JumpText: 0},
	{PlatformInfo: 0},
	{Browser: 0},
	{Solid: 0},
	{TemplateParts: 0},
	{Jewels: 0},
	{Spikes: 0},
	{SCROLLSPEEDBack: 0},
	{SCROLLSPEEDBackMid: 0},
	{SCROLLSPEEDBackMid2: 0},
	{SCROLLSPEEDFore: 0},
	{SCORE: 0},
	{GAMEOVER: 0},
	{CURRENT_INDEX: 0},
	{Desktop: 0},
	{GamePaused: 0},
	{Mobile: 0},
	{SPRINGBOARD: 0},
	{BLOCK_WIDTH: 0},
	{poppedTemplate: 0},
	{nextElligableForJewel: 0},
	{nextElligableForSpikes: 0},
	{nextElligableForSpringboard: 0},
	{partPlaced: 0},
	{jewelPlaced: 0},
	{spikePlaced: 0},
	{return_value: 0},
	{ix: 0}
];

self.InstanceType = {
	platform_regular: class extends self.ISpriteInstance {},
	platformIndustrial_: class extends self.ISpriteInstance {},
	platformIndustrial_10: class extends self.ISpriteInstance {},
	platformIndustrial_11: class extends self.ISpriteInstance {},
	platformIndustrial_12: class extends self.ISpriteInstance {},
	platformIndustrial_13: class extends self.ISpriteInstance {},
	platformIndustrial_14: class extends self.ISpriteInstance {},
	spike_up: class extends self.ISpriteInstance {},
	platformIndustrial_16: class extends self.ISpriteInstance {},
	platformIndustrial_17: class extends self.ISpriteInstance {},
	platformIndustrial_18: class extends self.ISpriteInstance {},
	platformIndustrial_19: class extends self.ISpriteInstance {},
	platformIndustrial_2: class extends self.ISpriteInstance {},
	platformIndustrial_20: class extends self.ISpriteInstance {},
	platformIndustrial_21: class extends self.ISpriteInstance {},
	platformIndustrial_22: class extends self.ISpriteInstance {},
	platformIndustrial_23: class extends self.ISpriteInstance {},
	platformIndustrial_24: class extends self.ISpriteInstance {},
	platformIndustrial_25: class extends self.ISpriteInstance {},
	spike_right: class extends self.ISpriteInstance {},
	spike_down: class extends self.ISpriteInstance {},
	spike_left: class extends self.ISpriteInstance {},
	platformIndustrial_3: class extends self.ISpriteInstance {},
	platformIndustrial_4: class extends self.ISpriteInstance {},
	platformIndustrial_5: class extends self.ISpriteInstance {},
	platformIndustrial_6: class extends self.ISpriteInstance {},
	platformIndustrial_7: class extends self.ISpriteInstance {},
	platformIndustrial_8: class extends self.ISpriteInstance {},
	platformIndustrial_9: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	PartQueue: class extends self.IArrayInstance {},
	Sequences: class extends self.IArrayInstance {},
	jewelOrange: class extends self.ISpriteInstance {},
	jewelPink: class extends self.ISpriteInstance {},
	jewelYellow: class extends self.ISpriteInstance {},
	debug_label: class extends self.ITextInstance {},
	destroyer: class extends self.ISpriteInstance {},
	Generator: class extends self.ISpriteInstance {},
	generic_text: class extends self.ITextInstance {},
	placeholder: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	puller: class extends self.ISpriteInstance {},
	score_text: class extends self.ITextInstance {},
	spawner: class extends self.ISpriteInstance {},
	PlayerKiller: class extends self.ISpriteInstance {},
	springBoard: class extends self.ISpriteInstance {},
	timerObject: class extends self.ISpriteInstance {},
	button_restart: class extends self.IWorldInstance {},
	dialog_background: class extends self.IWorldInstance {},
	help_text: class extends self.ITextInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Button: class extends self.IButtonInstance {},
	PauseText: class extends self.ITextInstance {},
	PauseButton: class extends self.ISpriteInstance {},
	Jump: class extends self.ISpriteInstance {},
	JumpText: class extends self.ITextInstance {},
	PlatformInfo: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	TemplateParts: class extends self.ISpriteInstance {},
	Jewels: class extends self.ISpriteInstance {},
	Spikes: class extends self.ISpriteInstance {}
}